name: safewalk
description: "Projeto em flutter de criação do SafeWalk, seu segurança virtual"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  http: ^1.2.1
  geolocator: ^13.0.1
  url_launcher: ^6.3.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/logo.png
  uses-material-design: true